//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NormalizacionPDF.Persistence.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domicilio
    {
        public long cuit { get; set; }
        public string tipo { get; set; }
        public string calle { get; set; }
        public string numero { get; set; }
        public int piso { get; set; }
        public string depto { get; set; }
        public string localidad { get; set; }
        public string cp { get; set; }
        public int telefono { get; set; }
        public string email { get; set; }
        public Nullable<int> idPlanta { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Planta Planta { get; set; }
    }
}
