//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NormalizacionPDF.Persistence.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Efluente
    {
        public string procesoGenerador { get; set; }
        public string componentesRelevantes { get; set; }
        public double volumen { get; set; }
        public string unidad { get; set; }
        public string unidadDeTiempo { get; set; }
        public string gestion { get; set; }
        public string cuerpoReceptor { get; set; }
        public int idPlanta { get; set; }
        public int idEfluente { get; set; }
    
        public virtual Planta Planta { get; set; }
    }
}
