//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NormalizacionPDF.Persistence.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmisionGaseosa
    {
        public string tipo { get; set; }
        public string emision { get; set; }
        public string procesoGenerador { get; set; }
        public string tratamiento { get; set; }
        public string componentesRelevantes { get; set; }
        public int idPlanta { get; set; }
        public int idEmisionGaseosa { get; set; }
    
        public virtual Planta Planta { get; set; }
    }
}
