//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NormalizacionPDF.Persistence.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormacionDePersonal
    {
        public int cantidadObreros { get; set; }
        public bool capacitacionObreros { get; set; }
        public int cantidadTecnicos { get; set; }
        public bool capacitacionTecnicos { get; set; }
        public int cantidadProfesionales { get; set; }
        public bool capacitacionProfesionales { get; set; }
        public int idPlanta { get; set; }
        public int idFormacionPersonal { get; set; }
    
        public virtual Planta Planta { get; set; }
    }
}
