//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NormalizacionPDF.Persistence.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insumo
    {
        public string nombre { get; set; }
        public string estadoFisico { get; set; }
        public double consumoAnual { get; set; }
        public string unidad { get; set; }
        public string almacenamiento { get; set; }
        public int idPlanta { get; set; }
        public int idInsumo { get; set; }
    
        public virtual Planta Planta { get; set; }
    }
}
