//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NormalizacionPDF.Persistence.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_TestingEntities : DbContext
    {
        public DB_TestingEntities()
            : base("name=DB_TestingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actividad> Actividads { get; set; }
        public virtual DbSet<actividadEmpresa> actividadEmpresas { get; set; }
        public virtual DbSet<Domicilio> Domicilios { get; set; }
        public virtual DbSet<Efluente> Efluentes { get; set; }
        public virtual DbSet<EmisionGaseosa> EmisionGaseosas { get; set; }
        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<FormacionDePersonal> FormacionDePersonals { get; set; }
        public virtual DbSet<GrupoActividad> GrupoActividads { get; set; }
        public virtual DbSet<Insumo> Insumoes { get; set; }
        public virtual DbSet<MateriaPrima> MateriaPrimas { get; set; }
        public virtual DbSet<Planta> Plantas { get; set; }
        public virtual DbSet<Representante> Representantes { get; set; }
        public virtual DbSet<ResiduosSolido> ResiduosSolidos { get; set; }
        public virtual DbSet<RiesgoPresunto> RiesgoPresuntoes { get; set; }
        public virtual DbSet<Subproducto> Subproductoes { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
    
        public virtual int createDB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("createDB");
        }
    }
}
