//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NormalizacionPDF.Persistence.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResiduosSolido
    {
        public string residuo { get; set; }
        public double cantidad { get; set; }
        public string unidad { get; set; }
        public string periodo { get; set; }
        public string procesoGenerador { get; set; }
        public string gestion { get; set; }
        public int idPlanta { get; set; }
        public int idResiduoSolido { get; set; }
    
        public virtual Planta Planta { get; set; }
    }
}
