//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NormalizacionPDF.Persistence.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiesgoPresunto
    {
        public bool fuentesMoviles { get; set; }
        public bool aparatosSometidos { get; set; }
        public bool sustanciasQuimicas { get; set; }
        public bool explosion { get; set; }
        public bool incendio { get; set; }
        public bool otro { get; set; }
        public string observaciones { get; set; }
        public int idPlanta { get; set; }
        public int idRiesgoPresunto { get; set; }
    
        public virtual Planta Planta { get; set; }
    }
}
